clone:
  path: github.com/jackspirou/tfs

build:
  image: golang:1.5.2
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - make build
    - make release

publish:
  github_release:
    image: jackspirou/drone-github-release
    checksums:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    api_key: $$GITHUB_TOKEN
    files:
      - tfs_*.tar.gz
    when:
      event: tag
