build:
  image: golang:1.5.2
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get github.com/mitchellh/gox
    - gox

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    files:
      - tfs_*
    when:
      branch: master
      event: tag
